### ISSUE TITLE
No module named 'basicsr.archs.gcfsr_arch'

### ISSUE THREAD

**Issue by deep-practice** [hejingwenhejingwen/GCFSR#10]
When running inference_gcfsr_blind.py, error occurs:
No module named 'basicsr.archs.gcfsr_arch'

**Comment by kambiannan** [comment]
path issue. from inside inference folder it cannot load the parent basicsr folder and therefore the model
copy that file to parent folder and try
eg. `cp inference/inference_gcfsr_blind.py .`
and then from root
`python3 inference_gcfsr_blind.py  --model_path experiments/pretrained_models/gcfsr_blind_512.pth --input inputs/sample`
instead of
`python3 inference/inference_gcfsr_blind.py  --model_path experiments/pretrained_models/gcfsr_blind_512.pth --input inputs/sample`
